apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    name: jenkins
  name: sample-pipeline
  namespace: technet
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'http://technet-gitlab-technet.apps.ocp4.technet.local/root/good-beer-backend.git'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
